### ISSUE TITLE
Does not work with Python 2.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nachstedt/sq100#39]
```
What steps will reproduce the problem?

1. Download the python package
2. Decompress it in a temporary directory
3. Start the tool: python ./gh600_console.py

What is the expected output? What do you see instead?

easjdp@easjdp8510:/tmp/gh625$ python ./gh600_console.py
Traceback (most recent call last):
  File "./gh600_console.py", line 4, in <module>
    from gh600 import GH600, ExportFormat, Utilities
  File "/tmp/gh625/gh600.py", line 12, in <module>
    from templates import Template
  File "/tmp/gh625/templates.py", line 133, in <module>
    from compiler.consts import SC_LOCAL, SC_GLOBAL, SC_FREE, SC_CELL
ImportError: cannot import name SC_GLOBAL
easjdp@easjdp8510:/tmp/gh625$ 



What version of the product are you using? On what operating system?

  build_186_py.zip
  Ubuntu 11.04
  Python 2.7.1+

Please provide any additional information below.

  The compiler module is deprecated since Python 2.6 and removed in Python 3.0

```

Original issue reported on code.google.com by `Jacques....@gmail.com` on 28 Jun 2011 at 9:29
